name: click_connect_flutter_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #state management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  material_design_icons_flutter: ^7.0.7296
  font_awesome_flutter: ^10.5.0
  feather_icons: ^1.2.0

  #Firebase
  cloud_firestore: ^4.8.5
  firebase_storage: ^11.2.6
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1

  #Service Locator
  get_it: ^7.6.0

  flutter_svg: ^2.0.7
  image_picker: ^1.0.2
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  fluttertoast: ^8.2.2
  modal_bottom_sheet: ^2.1.2
  go_router: ^10.1.0
  bloc: ^8.1.2
  dartz: ^0.10.1
  uuid: ^4.0.0
  selectable: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/.